PRAGMA foreign_keys = off;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS ssids ( ssid TEXT UNIQUE NOT NULL, new_ssid INTEGER NOT NULL DEFAULT 1, created_at TIMESTAMP NOT NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,user_created INT NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS ssid ON ssids (ssid);
COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
