BEGIN TRANSACTION;
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('xfinitywifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('XFINITY', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BTWifi-X', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BTWiFi-with-FON', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('linksys', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('<no ssid>', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('AndroidAP', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('UPC Wi-Free', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Ziggo', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('eduroam', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Telekom_FON', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BTWi-fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('iPhone', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Vodafone Hotspot', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FreeWifi_secure', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('optimumwifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('coxwifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FreeWifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 7490', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Vodafone Homespot', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Spectrum Mobile', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Virgin media', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('cablewifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('dlink', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TelenetWiFree', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MYChevrolet', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('KPN Fon', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('hpsetup', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('default', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('asus', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Guest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('\\ (Cloaked)', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SFR WiFi Mobile', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Home', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('orange', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Telstra AIR', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Fon WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SFR WiFi FON', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 6490 Cable', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('setup', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TELENETHOMESPOT', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('vodafone-WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BTWIFI', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Unitymedia WifiSpot', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TWCWiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Fritz!Box Fon WLAN 7390', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ShawMobileHotspot', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MEO-WIFI', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WLAN', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('telecentro WIFI', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('RedMi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('wireless', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumWiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('belkin54g', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('#NET-CLARO-WIFI', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 7362 SL', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WOW FI - FASTWEB', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('attwifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TWCWiFi-Passpoint', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumWiFi PluS', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box Gastzugang', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('optimumwifi_Passpoint', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('portthru', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('alticewifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('internet', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('PYUR Community', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('OutOfService', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Unifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('myGMC', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('walmartwifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('7483C2932C56', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box Fon WLAN 7360', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BTOpenzone', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('PROXIMUS_FON', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SWS1day', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('0001softbank', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('EAGLE', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('UPC WifiSpots', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('wifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Hilton Honors', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BTFON', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 7312', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Darmowe_Orange_WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Tp-link', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('PROXIMUS_AUTO_FON', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 7412', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('no_ssid', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('hhonors', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('????', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HEATKTE', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box Fon WLAN 7270', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 6360 Cable', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box Fon WLAN 7170', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netgear-guest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Gastzugang', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('KD WLAN Hotspot+', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SFR WiFi Public', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('skynet', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FON_ZON_FREE_INTERNET', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Concrete', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NOS_WIFI_Fon', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('_AUTO_ONOWiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ZyXEL', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ShawOpen', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('??', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('orange12', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box Fon WLAN 7112', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ASUS_5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Bouygues Telecom Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('office', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('bandsaw', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wi2premium', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Proximus Public Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('au_Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('byfly WIFI', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('demopool1', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Telekom', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('VOIP', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FON_BELGACOM', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('0000docomo', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR_EXT', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Lowes-Guest-WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('D-LINK', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BTOpenzone-H', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wi2premium_club', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ShawPasspoint', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('test', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('staff', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('steel', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('???', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('pretty fly for a wifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Free Public WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FON_FREE_INTERNET', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('COSMOTE WiFi Fon', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Horizon Wi-Free', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('demopool2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('0002softbank', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WiFi-Repeater', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('iptime', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Personal WiFi Zone', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BTOpenzone-B', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('eBOS', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Target Guest Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FON_NETIA_FREE_INTERNET', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('au_Wi-Fi2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Spectrum', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ACTIONTEC', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wi-Free', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Proximus Smart Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('O2 WIFI', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Walmartwifi_2.4', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SMC', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Casa', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('UPC Wi-Free', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('dd-wrt', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('guestnet', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 7330 SL', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TP-LINK_Extender', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Spectrum Free Trial', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('0001docomo', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('airportthru', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('dge', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('xerox', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('.FREE_Wi-Fi_PASSPORT', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('optimumwifi-Emergency', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('_ONOWiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Marriott_Guest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box Fon WLAN 7113', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DIRECT-', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('mobile', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ATT-WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DIR-615', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HomeNet', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('(null)', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('U+zone', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('freephonie', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BELTELECOM WIFI', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('_The Cloud', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('McDonalds Free WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('admin', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Motorola', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MyPlace', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Voice', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('PYUR 28B17', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('virus', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('101', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('iot', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('mywifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Private', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('M4m786iA', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WiFi_OBDii', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('iPhone (2)', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('My ASUS', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Gast', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Sprint Drive', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('?????', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('OTE WiFi Fon', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Sitecom', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Berlin autofrei', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('homewifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('KPN', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('wlan-ap', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('mycadillac', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WirelessNet', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('mybuick', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FBI Surveillance Van', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Subaru Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Netcomm Wireless', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ollehWiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('5ECUR3w3p5TOR3', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('public', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Dom', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('govroam', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Jt9x11w3', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('IPAD', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('guest-wifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Bright House Networks', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('rebar', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('PrettyFlyForAWiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('??????', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MarriottBonvoy_Guest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DIR-300NRU', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netgear11', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR24', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR22', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netgear69', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR23', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Netgear88', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR13', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netgear12', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR50', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netgear44', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('@Hyatt_WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR77', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('optimum', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR10', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR75', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR45', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR47', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR55', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR25', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR70', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR21', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR17', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR28', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR99', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Netgear57', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR19', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR20', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR49', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR43', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Orange_FunSpot', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR33', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR51', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR80', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR05', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR41', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR32', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR85', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR40', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Netgear18', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR48', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Netgear09', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR81', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR16', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR60', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR42', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR63', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR72', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR74', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR78', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Netgear91', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR73', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR89', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Netgear30', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netgear83', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netgear76', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netgear27', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR71', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR01', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR53', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR46', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR35', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR58', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR82', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR94', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR95', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR07', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netgear31', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR38', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR87', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR97', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR15', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR14', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR65', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR37', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR93', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netgear54', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR90', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR79', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR84', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR92', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netgear29', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR96', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box WLAN 3170', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR56', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR39', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR67', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR34', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR52', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR66', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR26', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR08', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR68', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR62', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('LjLr511', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Netgear61', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR64', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR86', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR36', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR06', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WirelessNet2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR04', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('<hidden ssid>', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR59', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR03', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR98', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box Fon WLAN 7320', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('VOO_HOMESPOT', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netgear02', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Alex', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR00', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WirelessICC', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Vodafone-Guest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 7272', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Home WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Telekom Fon', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('@wifi.id', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Shawgo', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Courtyard_Guest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('0', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Redmi 9A', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Swisscom_Auto_Login', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi48-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi88-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TMobileWingman', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi58-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi78-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi30-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi38-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi40-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi80-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi68-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi98-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi50-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi28-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi18-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi70-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi20-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFic8-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi10-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFia8-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFie8-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi08-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi60-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi00-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFic0-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi90-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('logitecuser', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFid0-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFia0-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Hotspot', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFid8-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('GABLE', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFib8-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFif8-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wi2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFif0-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFie0-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFib0-2G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Visitor', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HTC Portable Hotspot', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('swisscom', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('logitecgameuser', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box Fon WLAN 7240', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('netis', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BHN Secure', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('airport', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('swsecure', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('LWL-M', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 7330', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('CHT Wi-Fi(HiNet)', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WirelessLocal_IO', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('wirelessmobile', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Ikea WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DIR-300', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box WLAN 3270', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Student', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WirelessSGF', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MarriottBonvoy', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Oi WiFi Fon', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TENDA', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Draytek', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TCWireless', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('attwifi - Passpoint', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wi2_club', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MSHOME', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box Fon WLAN 7141', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('absauthz', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('House', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HUAWEI P30 Pro', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HHT-WM2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HHT-WM1', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('A9F1BDF1DAB1NVT4F4F59', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('CMCC', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('o2DSL', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('mycloud', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('X03B-89m6274IR', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('CHT Wi-Fi Auto', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Home Network', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Redmi Note 9 Pro', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Redmi Note 9', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TP-LINK_Extender_2.4GHz', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NetWork', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('3Com', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Telekom_SIM', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('CORP', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('sdp5g', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('CFA Private Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SKODA_WLAN', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('mesh', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Apple', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Tele Columbus', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('UBNT', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('nacho wifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('corporate', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Flow Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Mi Phone', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 6340 Cable', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('IHG Connect', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BYOD', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('GuestWiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('vehicle hotspot', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wireless-N', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('tsunami', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('freifunk', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('david', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('scandic_easy', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ZTE', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Maria', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BROADCOM_GUEST_0_6', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BROADCOM_GUEST_0_3', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('alpha', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HUAWEI P30 lite', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WirelessLocal', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Redmi 9', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HUAWEI P20 Pro', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('mint', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-80', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-88', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-40', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-98', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-50', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-78', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-E8', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-68', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-48', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Nachowifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Guest Network', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-70', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-90', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-30', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-18', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-58', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-10', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-B8', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-28', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-C8', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-08', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('redvest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-F8', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HomeSweetHome', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-60', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Home1', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Your New Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-20', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-38', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi58-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi88-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-D8', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi40-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi38-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi90-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi78-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi68-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 3272', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('eir_WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi80-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi30-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi70-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi48-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('yrneh09', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi08-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-A8', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ResidenceInn_GUEST', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Neuf WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-B0', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi98-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('family', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Ambassador_iPad', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi28-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('nomad5', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi60-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi50-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-E0', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi18-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi10-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFie8-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TrendNET', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFic8-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFia8-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-F0', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi00-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFi20-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('???????', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFic0-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('VW_WLAN', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFid0-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFia0-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFib8-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-A0', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('cisco', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFid8-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FON_FREE_EAP', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFie0-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-D0', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BROADCOM_GUEST_1_6', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFib0-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFif8-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MySpectrumWiFif0-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-C0', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DECO', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('tmobile', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SpectrumSetup-00', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('YOTA', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('tKeRl', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Guest_Access', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DigSig', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BROADCOM_GUEST_1_3', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DELTA WifiSpots', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('eero', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('martin', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('IHGConnect', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('#TELUS', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Linbury', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Speedport W 501V', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WLAN-TWDC', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Homenetwork', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('cWiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('#o4D@n!3LS3b@$+1@N<B', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Guests', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wi2eap', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Carbon', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('0000softbank', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ZMD_SAP', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Living Room TV', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('<Hidden Network>', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Starbucks WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('THOMSON', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Bill Wi the Science Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('T wifi zone', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FBI', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('dell_device', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('?MUSIC?', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('INTERSVYAZ_OPEN', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HOGWARTS', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SSID2-2.4', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('myhome', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Guest Wifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('serviceswifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BATCAVE', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HUAWEI P20 lite', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('102', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DIR-620', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SMITH', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('EdiMAX', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('CtLsIiClK', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MelitaWiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Johnson', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SYNC_00000000', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('myLGNet', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Vendor', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HUAWEI p8 lite', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('9qZNkCYGzf', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TP-LINK_Extender_5GHz', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('UqtbBHX4Tt', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('T wifi zone_secure', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Max', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('vodafone', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DANIEL', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('RSS-351540', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('mprotek', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('GovWiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Notes', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('JioPrivateNet', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BROADCOM_GUEST_0_5', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Sunshine', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Pretty Fly for a Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('oneteam', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('detnsw', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Powerline 540E', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MT_free', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BLUE', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ClubTotalplay_WiFi_2.4G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('.1.Free Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('net', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Matrix', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Tiscali', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ask4 Wireless', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('thomas', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('anna', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box WLAN 3131', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Green', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('it hurts when IP', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Red5', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ncpsp', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('LjLr11', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Philips WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Dmpm49Bjfk10', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('huawei', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Zoom', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ASK4 Wireless (802.1x)', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('wificlientesR', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SIP', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('samsung', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('_EUSKALTELWIFI_KALEAN', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('_BTWi-fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('router', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 3490', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Martin Router King', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Employee', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('VW WLAN', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('0A344ABB', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('mike', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Living Room', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('POS', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Michael', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('IWIFI', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('docomo', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Fairfield_Guest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FBI Surveillance', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('?MUSIC?', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('iPhone (3)', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('meijer-vendor', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('H&M Free WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ALICE-WLAN', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BROADCOM_GUEST_1_5', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Williams', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('flashzone-seamless', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Silverado', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('My WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Du()]C', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('maison', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('str241xipv', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BRCD25329', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box Fon WLAN 7050', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box WLAN 3370', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('L4m82az', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Redmi Note 10 Pro', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('zb0104p1', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('KaiserGuest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('CVWifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('george', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Knet', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WhiteSky-PublicWiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Linksys-G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('john', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Charlie', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ASUS_Guest1', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('doma', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('InS+0cK', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HUAWEI P10 lite', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Apple Store', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HUAWEI P10', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Free WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('m3connect', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ncpsh', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wi-Fi Auto Connect', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Fon', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('GDS VCI 01', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Redmi 9C NFC', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WIFI-Guest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR-5G-GUEST', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('LDSAccess', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Connectify-me', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Macysfreewifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Chromecast', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MINE', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Service', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Angel', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HOL ALU WLAN', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('freebox', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('????????', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('brown', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DG-Customer', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HOL_ZTE_4', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ConnectionPoint', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NTT-SPOT', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TPLINK', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('sweethome', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('notyourwifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Robert', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FBI Van', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('0001_Secured_Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Family Room TV', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DSL_2640NRU', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Hilton Honors Meeting', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('chris', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MikroTik', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('RED', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TELUS Passpoint', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Powerline 1260E', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('XFBSECA7HE6H', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Auto-BTWiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('VerizonWiFiAccess', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wireless@SGx', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Boingo Hotspot', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('@Gap Brands Free Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BETA', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Private WiFi Default', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('thuis', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR-2.4-G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WWM_P2P', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('p2pkoer', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Passpoint Secure', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Google WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Bella', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('rfcl13ntA', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Sam', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ChinaNet', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('.@ AIS SUPER WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HUAWEI P20', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('vendcust', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Moscow_WiFi_FREE', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('home2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wavlink-N', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('homebase', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('belkin', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('google', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('james', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('My Network', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ASDAFreeWifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('wmdemo', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('CMCC-AUTO', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NHS Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MobileConnect', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('CSL', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NetFasteR IAD 2 (PSTN)', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('AIS SMART Login', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ABC', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DATA', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR69-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('samsara', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('sage', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR50-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('comcast', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Renaissance_GUEST', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Android', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('IBIS', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DG-Employee', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR60-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Public WiFi Default', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DOM.RU Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('wilson', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR88-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DIR-320NRU', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR53-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR80-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wayport_Access', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Open', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR12-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR05-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR93-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR41-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('zg0104p1', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR75-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR58-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DG-Tablet', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Gamma', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR49-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('meijer-corp', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR74-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR65-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR25-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR11-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR91-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('study', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR86-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR23-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR27-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR37-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR47-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR81-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR72-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR45-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR51-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('delta', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR90-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR77-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR55-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR13-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR52-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR30-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR33-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR24-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR57-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR63-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR97-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR83-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR22-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR16-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR48-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('SMLL', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR73-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR94-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR28-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR71-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR43-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR18-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR96-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR10-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR07-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('jones', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR19-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR17-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR29-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G62', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR44-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR31-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR84-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR82-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR70-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR26-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR54-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR38-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR92-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR89-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR32-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR78-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR56-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR06-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR62-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR03-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR40-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR85-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR87-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR46-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR95-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR21-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR35-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR79-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR76-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR20-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR98-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR39-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR09-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR14-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR59-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR64-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR99-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR61-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Miller', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR15-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR67-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR42-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('King', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR66-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR34-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G22', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR08-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('internal', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR68-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR04-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('secure', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('.?MUSIC?', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR36-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 6320 Cable', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672GD2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Gateway', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G12', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G92', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR02-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR_Guest1', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('@BayernWLAN', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672GF2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('laQuinta', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G32', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G52', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Pod', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TkLrCp7', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G72', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672GA2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('CG-Guest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NON-RIS-PWL', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Telekom Fon WiFi HU', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR00-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HUAWEI Mate 20 Pro', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('1', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR01-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G02', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('tardis', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Marina', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HUAWEI P30', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('NETGEAR1', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DIR-300NRUB7', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G42', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672GB2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G82', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TELE2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('VIVACOM_NET', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672GC2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MCORP01', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672GE2', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('bob', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('t-mobile', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HUAWEI P smart 2019', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('VODAFONE_WIFI_108', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('wca001', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('orion', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('getyourownwifi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HEB Customer WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('conference', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('luna', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('[Washer] Samsung', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Sonos', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('BATMAN', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Invitados', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('.', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G12-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G22-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672GD2-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MERCURY', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G92-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G52-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672GF2-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G72-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G42-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672GA2-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('elena', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G82-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G02-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Wu-Tang LAN', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('04 and desert you', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G62-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672GB2-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672G32-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672GE2-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MO1875', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('TG1672GC2-5G', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('VIP', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('1040', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('jackson', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('HUAWEI P smart', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('taylor', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('eduSTAR', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('anderson', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('ctab', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('omega', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('MIGROS WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Radisson_Guest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('It burns when IP', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('[Range] Samsung', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Taco Bell WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('USR8054', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Boingo_Wireless', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box Fon WLAN 7340', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Nordstrom_Wi-Fi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('PHOENIX', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Airlive', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DSL-2640U', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('DOEguest', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('FRITZ!Box 3390', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('Kohls Guest WiFi', 1, 0, 1);
INSERT INTO ssids (ssid, new_ssid, created_at, user_created) VALUES ('WiFi4EU', 1, 0, 1);
COMMIT TRANSACTION;
